// Code generated by "stringer -type=MembershipStatus"; DO NOT EDIT.

package user

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNKNOWN_MS-0]
	_ = x[ACTIVE-1]
	_ = x[INACTIVE-2]
}

const _MembershipStatus_name = "UNKNOWN_MSACTIVEINACTIVE"

var _MembershipStatus_index = [...]uint8{0, 10, 16, 24}

func (i MembershipStatus) String() string {
	if i < 0 || i >= MembershipStatus(len(_MembershipStatus_index)-1) {
		return "MembershipStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MembershipStatus_name[_MembershipStatus_index[i]:_MembershipStatus_index[i+1]]
}
