// Code generated by "stringer -type=MembershipType"; DO NOT EDIT.

package user

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNKNOWN_MT-0]
	_ = x[FREE-1]
	_ = x[PAID-2]
}

const _MembershipType_name = "UNKNOWN_MTFREEPAID"

var _MembershipType_index = [...]uint8{0, 10, 14, 18}

func (i MembershipType) String() string {
	if i < 0 || i >= MembershipType(len(_MembershipType_index)-1) {
		return "MembershipType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MembershipType_name[_MembershipType_index[i]:_MembershipType_index[i+1]]
}
