// Code generated by "stringer -type=UserStatus"; DO NOT EDIT.

package user

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNKNOWN_US-0]
	_ = x[ACTIVE_US-1]
	_ = x[INACTIVE_US-2]
	_ = x[SUSPENDED_US-3]
}

const _UserStatus_name = "UNKNOWN_USACTIVE_USINACTIVE_USSUSPENDED_US"

var _UserStatus_index = [...]uint8{0, 10, 19, 30, 42}

func (i UserStatus) String() string {
	if i < 0 || i >= UserStatus(len(_UserStatus_index)-1) {
		return "UserStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UserStatus_name[_UserStatus_index[i]:_UserStatus_index[i+1]]
}
